### ISSUE TITLE
Live streams broken

### ISSUE THREAD

**Issue by piejanssens** [dersphere/plugin.video.nasa#13]

**Comment by jester-xbmc** [comment]
Known issue, NASA switched stream providers (again)

**Comment by piejanssens** [comment]
It's still on ustream, which is supported by Livestreamer.

You should use http://kodi.wiki/view/Add-on:Livestreamer and get the stream URL from it.

http://docs.livestreamer.io/cli.html#command-line-usage

It's as simple as 'livestreamer ustream.tv/NASAHDTV best' or 'livestreamer ustream.tv/NASAHDTV 720p' if you want to request a specific resolution.

**Comment by jester-xbmc** [comment]
how about you do a pull request :)
